openapi: 3.0.0
info:
  description: |
    Inventory API
  version: "1.0.0"
  title: Inventory 
servers:
- url: http://localhost:8501
paths:
  /item:
    post:
      tags:
        - item
      summary: Add a new item to the inventory
      operationId: addItem
      responses:
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/Item'
  '/items':
    get:
      tags:
        - items
      summary: Get all items 
      description: Returns multiple items
      operationId: getItems
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
        '500':
          description: Internal error

  '/item/{SKUId}':
    get:
      tags:
        - item
      summary: Find item 
      description: Returns a single item
      operationId: getItemById
      parameters:
        - name: SKUId
          in: path
          description: ID of item to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '400':
          description: Invalid ID supplied
        '404':
          description: Item not found
    put:
      tags:
        - item
      summary: Update an existing item 
      operationId: updateItem
      parameters:
        - name: SKUId
          in: path
          description: ID of item to update
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '400':
          description: Invalid ID supplied
        '404':
          description: Item not found
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/Item'

    delete:
      tags:
        - item
      summary: Deletes an item
      operationId: deleteItem
      parameters:
        - name: SKUId
          in: path
          description: Item id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
        SKUId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        status:
          type: string
          description: Item availability status
    Items:
      type: array
      items: 
        type: object 
  requestBodies:
    Item:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Item'
        application/xml:
          schema:
            $ref: '#/components/schemas/Item'
      description: Item object that needs to be added to the store
      required: true